# link to the source code of the bot
repo = 'https://github.com/Remnant-et-al/ivu-bot'

[roles]
# the role ID required to ban people
# this doesn't actually need to have any sort of permissions,
# it's just a marker for the bot.
organizer = 5678
# the role ID required to use the set-password command.
helper = 1234
# the role ID that will be granted to people that entered the password
grant = 9876
# the role ID that will be removed when the grant role is granted
# set to 0 to disable
remove = 0

[tokens]
discord = '...'
